### ISSUE TITLE
[BUG] Broken github link in froundry repository

### ISSUE THREAD

**Issue by mech-tools** [dovrosenberg/fvtt-autocomplete-mentions#4]
Hello,

The link to GitHub from within foundry package repository is broken: https://github.com/dovrosenberg/fvt--autocomplete-mentions

**Comment by dovrosenberg** [comment]
Thanks!  Can you point me to a link the page where the broken link is showing?  I can't find it anywhere.

**Comment by dovrosenberg** [comment]
![image](https://github.com/dovrosenberg/fvtt-autocomplete-mentions/assets/4704591/db6fb320-0977-4dc9-86c9-3d1e9d1cf2a8)

**Comment by mech-tools** [comment]
It's in the update quick recap:
![image](https://github.com/dovrosenberg/fvtt-autocomplete-mentions/assets/1687854/c227b583-a31b-4491-985e-1ab909130458)

**Comment by dovrosenberg** [comment]
Thanks. Found it.  Was it keeping you from updating?

I released 1.0.1 with a fix, but because it's an issue in the old package, I'm not sure if it will fix it or not.  I was able to successfully upgrade a local machine, so I'm hopeful it will work.

That link will still probably be broken until after you update

**Comment by mech-tools** [comment]
Can't reproduce as I can't update again.
